[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.20", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
proconio = "0.5.0"
axum = "0.6.4"
serde = { version = "1.0", features = ["derive"] }